version: '3.8'
services:
  backend:
    build:
      context: ./bookstore-api-server
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
    networks:
      - bookstore-network

  frontend:
    build:
      context: ./bookstore-frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    environment:
     - REACT_APP_API_URL=/api
    depends_on:
      - backend
    networks:
      - bookstore-network

networks:
  bookstore-network:
    driver: bridge