# backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore-backend
  template:
    metadata:
      labels:
        app: bookstore-backend
    spec:
      containers:
        - name: backend
          image: abdullahalshaad/bookstore-backend:2.0
          ports:
            - containerPort: 8081
          env:
            - name: CORS_ALLOWED_ORIGINS
              value: "http://localhost:3000"
            - name: PORT
              value: "8081"
---
# backend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: bookstore-backend
spec:
  selector:
    app: bookstore-backend
  ports:
    - port: 8081
      targetPort: 8081
---
# frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore-frontend
  template:
    metadata:
      labels:
        app: bookstore-frontend
    spec:
      containers:
        - name: frontend
          image: abdullahalshaad/bookstore-frontend:2.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_API_URL
              value: "/api"
---
# frontend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: bookstore-frontend
spec:
  type: NodePort
  selector:
    app: bookstore-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
