global:
  imagePullPolicy: "IfNotPresent"

frontend:
  replicaCount: 3
  image:
    tag: "3.0" 
  service:
    type: NodePort
   
backend:
  replicaCount: 3 
  image:
    tag: "3.0" 
  resources:
    requests:
      memory: "512Mi"
      cpu: "200m"
    limits:
      memory: "1024Mi"
      cpu: "1000m"
