global:
  namespace: bookstore
  imageRegistry: abdullahalshaad
  imagePullPolicy: Always
  # Default global version - can be used as a default image tag
  version: "3.0"
  tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"

frontend:
  enabled: true
  replicaCount: 1
  image:
    repository: "bookstore-frontend"
    tag: "3.0"
  env:
    REACT_APP_API_URL: "/api"
  service:
    type: ClusterIP
    port: 80
    #nodePort: 30000
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"

backend:
  enabled: true
  replicaCount: 1
  image:
    repository: "bookstore-backend"
    tag: "3.0"
  env:
    PORT: "8081"
  service:
    type: ClusterIP
    port: 8081
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"

# Ingress section moved to top level
ingress:
  enabled: true
  className: "nginx"
  host: "bookstore.example.com"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  tls: []