global:
  namespace: bookstore
  imageRegistry: abdullahalshaad
  imagePullPolicy: Always
  version: "2.0"
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  environments:
    production:
      replicas: 3
    staging:
      replicas: 1
  tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"

frontend:
  enabled: true
  replicaCount: 1
  image:
    repository: "bookstore-frontend"
    tag: "3.0"
  env:
    REACT_APP_API_URL: "/api"
  service:
    type: NodePort
    port: 80
    nodePort: 30000

backend:
  enabled: true
  replicaCount: 1
  image:
    repository: "bookstore-backend"
    tag: ""
  env:
    CORS_ALLOWED_ORIGINS: "http://localhost:3003"
    PORT: "8081"
  service:
    type: ClusterIP
    port: 8081