apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-backend
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore-backend
  template:
    metadata:
      labels:
        app: bookstore-backend
    spec:
      containers:
      - name: bookstore-backend
        image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        ports:
        - containerPort: {{ .Values.service.port }}
        env:
        - name: CORS_ALLOWED_ORIGINS
          value: "{{ .Values.env.CORS_ALLOWED_ORIGINS }}"
        - name: PORT
          value: "{{ .Values.env.port }}"
