apiVersion: v1
kind: Service
metadata:
  name: bookstore-backend
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: bookstore-backend
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
