apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-frontend
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore-frontend
  template:
    metadata:
      labels:
        app: bookstore-frontend
    spec:
      containers:
      - name: bookstore-frontend
        image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        ports:
        - containerPort: {{ .Values.service.port }}
        env:
        - name: REACT_APP_API_URL
          value: "{{ .Values.env.REACT_APP_API_URL }}"
        - name: http_backend_url
          value: {{ .Values.backendUrl | quote }} 
