apiVersion: v1
kind: Service
metadata:
  name: bookstore-frontend
  namespace: {{ .Values.global.namespace }}
spec:
  type: NodePort
  selector:
    app: bookstore-frontend
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    nodePort: {{ .Values.service.nodePort }}
