# Default values that can be overridden by parent chart
enabled: true
replicaCount: 1
image:
  imageRegistry: abdullahalshaad
  repository: bookstore-frontend
  tag: latest
  pullPolicy: IfNotPresent
env: {}
service:
  type: NodePort
  port: 80
  nodePort: 30000
